site:
  theme: vividigit
  language: en

navigation:
  order:
    - "/"
    - services
    - categories
    - solutions
    - cases
    - team
    - industries
    - countries
    - languages
    - blog
    - contact

entities:
  types:
    - service
    - specialist
    - case
    - solution
    - category
    - industry
    - country
    - language

facets:
  dimensions:
    - categories
    - industries
    - countries
    - languages

exports:
  language_code_map:
    english: EN
    german: DE
    french: FR
    spanish: ES
    russian: RU
    chinese: ZH
    japanese: JA
    italian: IT
    portuguese: PT
